
CREATE DATABASE CinemasPIM;
/*Creates Table*/
CREATE TABLE cadeiras (id INT AUTO_INCREMENT NOT NULL, id_sala_id INT NOT NULL, linha VARCHAR(20) NOT NULL, columna INT NOT NULL, INDEX IDX_7081F4C61B81764F (id_sala_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE cards (id INT AUTO_INCREMENT NOT NULL, id_cliente_id INT NOT NULL, nome VARCHAR(255) NOT NULL, card_number VARCHAR(255) NOT NULL, secure_number VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_4C258FD7BF9CE86 (id_cliente_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE cinemas (id INT AUTO_INCREMENT NOT NULL, id_endereco_id INT NOT NULL, nome VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_D7D63B9A3A5A5D4 (id_endereco_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE clientes (id INT AUTO_INCREMENT NOT NULL, endereco_id INT NOT NULL, cpf VARCHAR(255) NOT NULL, telefone VARCHAR(255) NOT NULL, use_card TINYINT(1) DEFAULT NULL, use_pimcoin TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_50FE07D71BB76823 (endereco_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE endereco (id INT AUTO_INCREMENT NOT NULL, rua VARCHAR(255) NOT NULL, cidade VARCHAR(255) NOT NULL, estado VARCHAR(50) NOT NULL, cpe VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE filme (id INT AUTO_INCREMENT NOT NULL, cinemas_id INT DEFAULT NULL, titulo VARCHAR(255) NOT NULL, categorias VARCHAR(255) NOT NULL, duration VARCHAR(255) NOT NULL, ano_estreia INT NOT NULL, rating INT NOT NULL, INDEX IDX_3A387F00C5C76018 (cinemas_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE ingressos (id INT AUTO_INCREMENT NOT NULL, filme_id INT NOT NULL, cinema_id INT NOT NULL, id_filme_id INT NOT NULL, id_cadeira_id INT NOT NULL, id_order_id INT DEFAULT NULL, horario VARCHAR(255) NOT NULL, valor DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_8ED539D1E6E418AD (filme_id), INDEX IDX_8ED539D1B4CB84B6 (cinema_id), INDEX IDX_8ED539D1B63FF438 (id_filme_id), UNIQUE INDEX UNIQ_8ED539D1C946E4F (id_cadeira_id), INDEX IDX_8ED539D1DD4481AD (id_order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE `order` (id INT AUTO_INCREMENT NOT NULL, id_pagamento_id INT NOT NULL, id_cliente_id INT NOT NULL, UNIQUE INDEX UNIQ_F5299398C3AEF485 (id_pagamento_id), INDEX IDX_F52993987BF9CE86 (id_cliente_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE pagamento (id INT AUTO_INCREMENT NOT NULL, id_cliente_id INT DEFAULT NULL, use_pimcoin TINYINT(1) DEFAULT NULL, use_card TINYINT(1) DEFAULT NULL, valor DOUBLE PRECISION NOT NULL, INDEX IDX_3E1F4B167BF9CE86 (id_cliente_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE pim_coin (id INT AUTO_INCREMENT NOT NULL, id_cliente_id INT NOT NULL, private_key_user VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_AD584B107BF9CE86 (id_cliente_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE sala (id INT AUTO_INCREMENT NOT NULL, id_cinema_id INT NOT NULL, horarios VARCHAR(255) NOT NULL, INDEX IDX_E226041C34FE3891 (id_cinema_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
CREATE TABLE usuarios (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB

ALTER TABLE cadeiras ADD CONSTRAINT FK_7081F4C61B81764F FOREIGN KEY (id_sala_id) REFERENCES sala (id)
ALTER TABLE cards ADD CONSTRAINT FK_4C258FD7BF9CE86 FOREIGN KEY (id_cliente_id) REFERENCES clientes (id)
ALTER TABLE cinemas ADD CONSTRAINT FK_D7D63B9A3A5A5D4 FOREIGN KEY (id_endereco_id) REFERENCES endereco (id)
ALTER TABLE clientes ADD CONSTRAINT FK_50FE07D71BB76823 FOREIGN KEY (endereco_id) REFERENCES endereco (id)
ALTER TABLE filme ADD CONSTRAINT FK_3A387F00C5C76018 FOREIGN KEY (cinemas_id) REFERENCES cinemas (id)
ALTER TABLE ingressos ADD CONSTRAINT FK_8ED539D1E6E418AD FOREIGN KEY (filme_id) REFERENCES filme (id)
ALTER TABLE ingressos ADD CONSTRAINT FK_8ED539D1B4CB84B6 FOREIGN KEY (cinema_id) REFERENCES cinemas (id)
ALTER TABLE ingressos ADD CONSTRAINT FK_8ED539D1B63FF438 FOREIGN KEY (id_filme_id) REFERENCES filme (id)
ALTER TABLE ingressos ADD CONSTRAINT FK_8ED539D1C946E4F FOREIGN KEY (id_cadeira_id) REFERENCES cadeiras (id)
ALTER TABLE ingressos ADD CONSTRAINT FK_8ED539D1DD4481AD FOREIGN KEY (id_order_id) REFERENCES `order` (id)
ALTER TABLE `order` ADD CONSTRAINT FK_F5299398C3AEF485 FOREIGN KEY (id_pagamento_id) REFERENCES pagamento (id)
ALTER TABLE `order` ADD CONSTRAINT FK_F52993987BF9CE86 FOREIGN KEY (id_cliente_id) REFERENCES clientes (id)
ALTER TABLE pagamento ADD CONSTRAINT FK_3E1F4B167BF9CE86 FOREIGN KEY (id_cliente_id) REFERENCES clientes (id)
ALTER TABLE pim_coin ADD CONSTRAINT FK_AD584B107BF9CE86 FOREIGN KEY (id_cliente_id) REFERENCES clientes (id)
ALTER TABLE sala ADD CONSTRAINT FK_E226041C34FE3891 FOREIGN KEY (id_cinema_id) REFERENCES cinemas (id)

ALTER TABLE ingressos DROP FOREIGN KEY FK_8ED539D1B63FF438
DROP INDEX IDX_8ED539D1B63FF438 ON ingressos
ALTER TABLE ingressos DROP id_filme_id

ALTER TABLE clientes ADD id_usuario_id INT NOT NULL
ALTER TABLE clientes ADD CONSTRAINT FK_50FE07D77EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES usuarios (id)
CREATE UNIQUE INDEX UNIQ_50FE07D77EB2C349 ON clientes (id_usuario_id)


ALTER TABLE pim_coin CHANGE private_key_user private_key_user VARCHAR(1000) NOT NULL

ALTER TABLE usuarios ADD admin TINYINT(1) DEFAULT NULL
CREATE TABLE ingressos_filme (ingressos_id INT NOT NULL, filme_id INT NOT NULL, INDEX IDX_3F72F9C012373158 (ingressos_id), INDEX IDX_3F72F9C0E6E418AD (filme_id), PRIMARY KEY(ingressos_id, filme_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
ALTER TABLE ingressos_filme ADD CONSTRAINT FK_3F72F9C012373158 FOREIGN KEY (ingressos_id) REFERENCES ingressos (id) ON DELETE CASCADE
ALTER TABLE ingressos_filme ADD CONSTRAINT FK_3F72F9C0E6E418AD FOREIGN KEY (filme_id) REFERENCES filme (id) ON DELETE CASCADE
ALTER TABLE ingressos DROP FOREIGN KEY FK_8ED539D1E6E418AD
DROP INDEX UNIQ_8ED539D1E6E418AD ON ingressos
ALTER TABLE ingressos DROP filme_id